//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily
    {
        public Daily()
        {
            this.PXsach = new HashSet<PXsach>();
            this.Phieuthusach = new HashSet<Phieuthusach>();
        }
    
        public string Madaily { get; set; }
        public string Tendaily { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public long No { get; set; }
    
        public virtual ICollection<PXsach> PXsach { get; set; }
        public virtual ICollection<Phieuthusach> Phieuthusach { get; set; }
    }
}
