//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQLPhatHanhSachEntities : DbContext
    {
        public DBQLPhatHanhSachEntities()
            : base("name=DBQLPhatHanhSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CTPNsach> CTPNsach { get; set; }
        public DbSet<CTPXsach> CTPXsach { get; set; }
        public DbSet<CTphieuchiNXB> CTphieuchiNXB { get; set; }
        public DbSet<Daily> Daily { get; set; }
        public DbSet<Nhaxuatban> Nhaxuatban { get; set; }
        public DbSet<PNsach> PNsach { get; set; }
        public DbSet<PXsach> PXsach { get; set; }
        public DbSet<PhieuchiNXB> PhieuchiNXB { get; set; }
        public DbSet<Phieuthusach> Phieuthusach { get; set; }
        public DbSet<Sach> Sach { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TTbansachDL> TTbansachDL { get; set; }
        public DbSet<TheLoai> TheLoai { get; set; }
        public DbSet<CTPhieuDat> CTPhieuDat { get; set; }
        public DbSet<PhieuDatSach> PhieuDatSach { get; set; }
        public DbSet<TaiKhoanDaiLy> TaiKhoanDaiLy { get; set; }
    }
}
