//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhaxuatban
    {
        public Nhaxuatban()
        {
            this.PNsach = new HashSet<PNsach>();
            this.PhieuchiNXB = new HashSet<PhieuchiNXB>();
            this.Sach = new HashSet<Sach>();
        }
    
        public string MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public long No { get; set; }
        public string Sotaikhoan { get; set; }
    
        public virtual ICollection<PNsach> PNsach { get; set; }
        public virtual ICollection<PhieuchiNXB> PhieuchiNXB { get; set; }
        public virtual ICollection<Sach> Sach { get; set; }
    }
}
