//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuchiNXB
    {
        public PhieuchiNXB()
        {
            this.CTphieuchiNXB = new HashSet<CTphieuchiNXB>();
        }
    
        public string Maphieuchi { get; set; }
        public string MaNXB { get; set; }
        public System.DateTime Ngay { get; set; }
        public long Tongtien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<CTphieuchiNXB> CTphieuchiNXB { get; set; }
        public virtual Nhaxuatban Nhaxuatban { get; set; }
    }
}
