//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatSach
    {
        public PhieuDatSach()
        {
            this.CTPhieuDat = new HashSet<CTPhieuDat>();
            this.PXsach = new HashSet<PXsach>();
        }
    
        public string MaPhieuDat { get; set; }
        public string Madaily { get; set; }
        public System.DateTime NgayDat { get; set; }
        public long TongTien { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<CTPhieuDat> CTPhieuDat { get; set; }
        public virtual Daily Daily { get; set; }
        public virtual ICollection<PXsach> PXsach { get; set; }
    }
}
