//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXsach
    {
        public PXsach()
        {
            this.CTPXsach = new HashSet<CTPXsach>();
        }
    
        public string MaPX { get; set; }
        public string Madaily { get; set; }
        public System.DateTime Ngayxuat { get; set; }
        public long Tongtien { get; set; }
        public string Nguoinhan { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual ICollection<CTPXsach> CTPXsach { get; set; }
        public virtual Daily Daily { get; set; }
    }
}
